version: "3.7"

services:
  server:
    build: "./back"
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
    - "serv-vol:/root/"
    ports:
      - "8080:8080"
    networks:
      - server-tier
    restart: on-failure

  client_mobile:
   build: "./mobile/"
   ports:
     - "8082:8082"
   depends_on:
     - server
     - client_web
   volumes:
     - "/user/mobile/:/client-vol/user/"
   networks:
     - web-tier
   restart: on-failure

  client_web:
    container_name: client_web
    build:
      context: ./front/
      dockerfile: Dockerfile.front
    ports:
      - '8081:8080'
    networks:
      - web-tier
    restart: on-failure

volumes:
  client-vol:
  serv-vol:

networks:
  server-tier:
  web-tier: