# Generated by Django 3.1.5 on 2021-03-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_auto_20210306_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newsPapper',
            new_name='newsPaper',
        ),
    ]
