# Generated by Django 3.1.5 on 2021-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0004_auto_20210307_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='mail',
        ),
        migrations.AddField(
            model_name='film',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
