# Generated by Django 3.1.5 on 2021-03-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0005_auto_20210307_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='data',
            new_name='date',
        ),
    ]
