# Generated by Django 3.1.5 on 2021-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0006_auto_20210307_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netflix',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
